### ISSUE TITLE
process stops after first step

### ISSUE THREAD

**Issue by binnichtaktiv** [Co2333/AppleSiliconUIKitPatch#1]
idk why but I installed Xcode and Xcode command line tools and did chmod +x. 
<img width="570" alt="grafik" src="https://user-images.githubusercontent.com/96953964/168793309-62b370cc-53ac-4df5-97b2-7515fa7b5541.png">
im on macos 12.3.1

**Comment by binnichtaktiv** [comment]
tried to unzip it and tried it with the .app bundle still not working :(

**Comment by Lakr233** [comment]
try to add a line at the second line of the script under the # line

`
set -ex
`

this will open the debug mode and let's see what is going on

**Comment by binnichtaktiv** [comment]
> try to add a line at the second line of the script under the # line
> 
> `set -ex`
> 
> this will open the debug mode and let's see what is going on

Last login: Wed May 18 14:41:37 on ttys000
jonasb.@iMacvonJonas ~ % cd /Users/jonasb./Documents/tiktok/AppleSiliconUIKitPatch-1.0.0
jonasb.@iMacvonJonas AppleSiliconUIKitPatch-1.0.0 % chmod +x patch.sh
jonasb.@iMacvonJonas AppleSiliconUIKitPatch-1.0.0 % ./patch.sh tiktok.ipa
+ set -e
++ dirname ./patch.sh
+ cd .
++ pwd
+ WORKING_LOCATION=/Users/jonasb./Documents/tiktok/AppleSiliconUIKitPatch-1.0.0
+ cd /Users/jonasb./Documents/tiktok/AppleSiliconUIKitPatch-1.0.0
+ echo '[i] working location: /Users/jonasb./Documents/tiktok/AppleSiliconUIKitPatch-1.0.0'
[i] working location: /Users/jonasb./Documents/tiktok/AppleSiliconUIKitPatch-1.0.0
+ echo '[*] checking for dependencies...'
[*] checking for dependencies...
+ REQUIRED_BINARY_LIST=("ldid" "vtool" "otool" "install_name_tool" "unzip" "codesign" "plutil")
+ BROKEN=false
+ for BINARY in '"${REQUIRED_BINARY_LIST[@]}"'
++ which ldid
+ LOCATION=
jonasb.@iMacvonJonas AppleSiliconUIKitPatch-1.0.0 %

**Comment by binnichtaktiv** [comment]
is ldid missing or what?

**Comment by binnichtaktiv** [comment]
lol it worked now but the app crashes on launch😭

**Comment by binnichtaktiv** [comment]
its working now
W

**Comment by VityaSchel** [comment]
How did you resolve this? I have the exact same output after setting `set -ex`
